version: '3'
services:
    server:
        image: php:7.4-cli
        working_dir: /app
        entrypoint: /usr/local/bin/php
        command: server.php
        volumes:
            - ./:/app

    client:
        image: php:7.4-cli
        working_dir: /app
        entrypoint: /usr/local/bin/php
        command: client.php
        volumes:
            - ./:/app

